# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PsiFPOP_cpp <- function(y, beta, alpha, sampling_method, sampling_method_parameter, wt) {
    .Call(`_PsiFPOP_PsiFPOP_cpp`, y, beta, alpha, sampling_method, sampling_method_parameter, wt)
}

PsiOP_cpp <- function(y, beta, alpha, wt) {
    .Call(`_PsiFPOP_PsiOP_cpp`, y, beta, alpha, wt)
}

